import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import { auth } from '../app/firebase'
import { getAuth, createUserWithEmailAndPassword, signOut } from 'firebase/auth'
import { useEffect } from 'react'
export default function Home ({ properties }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
      </div>
      <section className='home'>
        <Image
          src='/home1.jpg'
          alt='Picture of the author'
          width={912}
          height={768}
        />
      </section>
    </>
  )
}
