import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { fetchAPI } from "./api/hello";

const VR = dynamic(() => import("../components/VR"), { ssr: false });
export default function Home({ properties }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VR properties={properties} />
    </div>
  );
}
export async function getServerSideProps() {
  const properties = await fetchAPI("/properties");
  return { props: { properties } };
}
